### ISSUE TITLE
Simulation does not answer to demand

### ISSUE THREAD

**Issue by RackieW** [johnytoxic/CSL2DemandControl#1]
Probably aware and not an "issue" as the mod not doing what it goes out to do right, however it does make this mod at its current stage pretty useless. While the demand goes up and buildings built, it will not make people or companies move in so the result is the buildings just getting abandoned straight away, as unlike in the first game people do not move in to a building just because it is placed/built.

**Comment by johnytoxic** [comment]
This is something I was kinda expecting or have experienced before. As mentioned before, the simulation in CS2 is way more complex than it is in CS1. It's hard to exactly pin down all factors, that are required for e.g. the office zones to build. But I can try and change these factors as well; I'll have a look at it.

Do you think it would fix some problems, when there is also an infinite "demand" of people moving in? Put in to other words: every built residential zone will be immediately filled by people. Please note that this might incur other problems (e.g. unemployment, more demand in infrastructure like hospitals, etc.), which the player has to deal with.

**Comment by Shy-Adam** [comment]
hey, sorry for interfering, but being able to freely create residentials would help control the unemployment issue as well.

**Comment by RackieW** [comment]
I think population is a first great step and the most important; as with population increase actual demands for other zoning (industrial/commercial) would also increase and they would start popping in after a while, thered be some issues but nothing that couldn't be fixed under time as normal gameplay.

The way it's implemented is of less importance, if it's automatically filling up built residential places (as in the first game) or if it was somehow possible to create a magic "i want X amount of residents" button. However I do not think there are such numbers/definites in the code and as you say the simulation is much more complex.

However somehow there seems to be a soft limit of sorts in amount of people moving in: for example even with all demands full, a lot of built unoccupied buildings, all services accounted for people & companies still move in at a very slow rate. At maximum I've seen around 300/hour, but usually around 200.

99% of buildings stay empty (if zone an unreasonably large new zone), get abandoned and collapse. This with the "super fast building" enabled in devmode, less dramatic but similiar results with slower (normal) building rate. Contra to the first game where if one forced a residential building, citizens would fill it up almost instantly

**Comment by Jackzilla321** [comment]
hi, i also would prefer if this mod was paired with instant full occupancy - i used it to try to go very quickly in an NYC simulator, only to find that i really should've just 'played the game' anyways - doing slow low-zoning build up and then eventually upzoning. At that point though, the mod is a useful aesthetic addition for taking screenshots, which is maybe a separate use case than people like me are looking for.

**Comment by johnytoxic** [comment]
I've released a new version, which now sets the household demand. You can download it from the [release page](https://github.com/johnytoxic/CSL2DemandControl/releases/tag/beta-1.0.2) or via the [Thunderstore app](https://thunderstore.io/c/cities-skylines-ii/p/johnytoxic/Infinite_Demand_Mod/).

Could you please check, whether this fixes you issue?

I've also noticed more parameters, like _EducatedWorkforce_, _CompanyWealth_, _FreeWorkplaces_, _Unemployment_, and so on. I'd expect these to take some more intense testing and tuning, before I'm confident to change them!

**Comment by RackieW** [comment]
> I've released a new version, which now sets the household demand. You can download it from the [release page](https://github.com/johnytoxic/CSL2DemandControl/releases/tag/beta-1.0.2) or via the [Thunderstore app](https://thunderstore.io/c/cities-skylines-ii/p/johnytoxic/Infinite_Demand_Mod/).
> 
> Could you please check, whether this fixes you issue?
> 
> I've also noticed more parameters, like _EducatedWorkforce_, _CompanyWealth_, _FreeWorkplaces_, _Unemployment_, and so on. I'd expect these to take some more intense testing and tuning, before I'm confident to change them!

Cool, was thinking of uninstalling the game since I dont play it but ill check this out! I wonder if those parameters even can be changed without breaking as they are supposed to mimic how its actually in the city, but interesting for sure

**Comment by RackieW** [comment]
Tried, and wow.
Does not fix the whole problem no, its not like in the first game still, but its as good as I hoped. Huge difference to previously, got 3-5 more/faster people moving in now

**Comment by Jackzilla321** [comment]
Huge improvement towards the use I was hoping for, thank you so much! Still
not an instant magic wand but makes the volume of pop growth so big that
the constraint becomes time spent in simulation rather than endlessly
battling abandoned buildings

**Comment by johnytoxic** [comment]
Great!

I'm closing the issue for now, because it seems some of the issue haven been fixed or are at least acceptable. I still need to tackle the overall demand adjustments, which are very complex.
